"""Las migraciones crean el esquema completo, coinciden con los modelos
y se aplican sobre una base de datos que ya tiene datos.

Por defecto usan SQLite. En CI también se ejecutan contra PostgreSQL
definiendo MIGRATION_TEST_DATABASE_URL (base de datos vacía y desechable).
"""

import os

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, text

from app.config import Settings, get_settings


@pytest.fixture
def migration_db(tmp_path, monkeypatch):
    url = os.environ.get("MIGRATION_TEST_DATABASE_URL") or f"sqlite:///{tmp_path / 'm.db'}"
    url = Settings.use_psycopg_driver(url)
    monkeypatch.setattr(get_settings(), "database_url", url)
    config = Config("alembic.ini")
    command.downgrade(config, "base")  # parte siempre de una base vacía
    yield config, url
    command.downgrade(config, "base")


def test_upgrade_matches_models(migration_db):
    config, _ = migration_db
    command.upgrade(config, "head")
    try:
        command.check(config)  # falla si los modelos cambian sin nueva migración
    except AutogenerateDiffsDetected as error:
        pytest.fail(f"Falta una migración: {error}")


def test_upgrade_with_existing_data(migration_db):
    """Cada migración debe poder aplicarse sobre datos reales (columnas nuevas con default)."""
    config, url = migration_db
    first = ScriptDirectory.from_config(config).get_base()
    command.upgrade(config, first)
    engine = create_engine(url)
    with engine.begin() as conn:
        conn.execute(text("INSERT INTO modules (slug, title, position) VALUES ('m', 'M', 1)"))
        conn.execute(
            text(
                "INSERT INTO lessons (slug, module_id, title, position, sources) "
                "VALUES ('l', 1, 'L', 1, '[]')"
            )
        )
        conn.execute(
            text(
                "INSERT INTO users (email, password_hash, display_name) VALUES ('a@b.c', 'x', 'A')"
            )
        )
    command.upgrade(config, "head")
    with engine.connect() as conn:
        version = conn.execute(text("SELECT token_version FROM users")).scalar_one()
        in_browser = conn.execute(text("SELECT example_in_browser FROM lessons")).scalar_one()
    engine.dispose()
    assert version == 0
    assert in_browser in (True, 1)
