"""rgpd, recuperacion de contrasena y ejercicios

Revision ID: 633542ddf0c6
Revises: 94b62e22be5a
Create Date: 2026-09-25 23:07:07.193464

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "633542ddf0c6"
down_revision: str | Sequence[str] | None = "94b62e22be5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_password_reset_tokens_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.add_column(sa.Column("starter", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("example_stdin", sa.Text(), server_default="", nullable=False)
        )
        batch_op.add_column(
            sa.Column("exercise_stdin", sa.Text(), server_default="", nullable=False)
        )
        batch_op.add_column(
            sa.Column("example_in_browser", sa.Boolean(), server_default=sa.true(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("checks", sa.JSON(), server_default=sa.text("'[]'"), nullable=False)
        )
        batch_op.add_column(
            sa.Column("assistant", sa.JSON(), server_default=sa.text("'{}'"), nullable=False)
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("privacy_accepted_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("token_version", sa.Integer(), server_default="0", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("token_version")
        batch_op.drop_column("privacy_accepted_at")

    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.drop_column("assistant")
        batch_op.drop_column("checks")
        batch_op.drop_column("example_in_browser")
        batch_op.drop_column("exercise_stdin")
        batch_op.drop_column("example_stdin")
        batch_op.drop_column("starter")

    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_password_reset_tokens_user_id"))

    op.drop_table("password_reset_tokens")
    # ### end Alembic commands ###
