"""quiz y retos

Revision ID: c8f7da35ecbb
Revises: 633542ddf0c6
Create Date: 2026-09-26 01:57:09.222107

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8f7da35ecbb"
down_revision: str | Sequence[str] | None = "633542ddf0c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("quiz", sa.JSON(), server_default=sa.text("'[]'"), nullable=False)
        )
        batch_op.add_column(
            sa.Column("challenge", sa.JSON(), server_default=sa.text("'{}'"), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.drop_column("challenge")
        batch_op.drop_column("quiz")

    # ### end Alembic commands ###
